version: '2'
services:
  elasticsearch:
    image: elasticsearch:latest
    entrypoint: /tmp/elasticEntry.sh
    command: elasticsearch -Des.network.host=0.0.0.0
    ports: 
      - "9200:9200"
    volumes:
      - ./:/tmp
  logstash:
    image: logstash:latest
    entrypoint: /tmp/logstashEntry.sh
    volumes:
      - ./:/tmp
    depends_on:
     - elasticsearch
    links:
      - elasticsearch
  kibana:
    image: kibana:latest
    ports:
      - "5601:5601"
    links:
      - elasticsearch
