version: '2'
services:
  elasticsearch:
    image: elasticsearch:latest
  logstash:
    build: 
      context: ./
      dockerfile: Dockerfile.logstash
    entrypoint: /tmp/logstashEntry.sh
    volumes:
      - ./:/tmp
    depends_on:
     - elasticsearch
    links:
      - elasticsearch
  kibana:
    image: kibana:latest
    ports:
      - "5601:5601"
    links:
      - elasticsearch
